[package]
name = "process-runner"
description = "Automatically run processes in the background on start-up."
version = "0.1.1"
edition = "2021"

[dependencies]
config = { version = "0.14.0", features = ["toml"] }
simple-log = "1.6.0"
special-folder = "0.2.2"
mslnk = "0.1.8"
