[package]
name = "process-runner"
description = "Automatically run processes in the background on start-up."
version = "0.1.0"
edition = "2021"

[dependencies]
auto-launch = "0.5.0"
config = { version = "0.14.0", features = ["toml"] }
simple-log = "1.6.0"
